language: ruby
node_js:
  - "12"

cache:
  bundler: true
  directories:
    - node_modules

before_install:
  - gem install sass
  - npm i

script:
  - npm test

sudo: false

notifications:
  email: false
